export const data = [
  {
    id: "a1b2c3d4e5f6g7h8i9j0",
    name: "Hoa Lac",
    code: "HL",
    address: "Hoa Lac Hi-tech Park, Km29 Đại lộ Thăng Long, Thạch Hoà, Thạch Thất, Hà Nội ",
    phone: "0987654321",
    email: "abc@fpt.edu.vn",
    status: "Active",
  },
  {
    id: "k1l2m3n4o5p6q7r8s9t0",
    name: "Ho Chi Minh",
    code: "HCM",
    address: "Lô E2a-7, D1, Long Thạnh Mỹ, TP. Thủ Đức, Hồ Chí Minh",
    phone: "0987654321",
    email: "abc@fpt.edu.vn",
    status: "Disactive",
  },
  {
    id: "u1v2w3x4y5z6a7b8c9d0",
    name: "Quy Nhon",
    code: "QN",
    address: "R639+HM2, Khu đô thị mới, Quy Nhơn, Bình Định",
    phone: "0123456789",
    email: "qn@fpt.edu.vn",
    status: "Active",
  },
  {
    id: "e1f2g3h4i5j6k7l8m9n0",
    name: "Da Nang",
    code: "DN",
    address: "FPT City, Ngũ Hành Sơn, Da Nang",
    phone: "0123456789",
    email: "dn@fpt.edu.vn",
    status: "Active",
  },
  {
    id: "o1p2q3r4s5t6u7v8w9x0",
    name: "Can Tho",
    code: "CT",
    address: "600 Nguyễn Văn Cừ Nối Dài, An Bình, Bình Thủy, Cần Thơ",
    phone: "0123456789",
    email: "ct@fpt.edu.vn",
    status: "Active",
  },
];
