import { Topic } from "@/app/student/topics/type";

export const topics: Topic[] = [
    {
        enName: "FUC - Capstone management system for FPT university teachers and students",
        vnName: "FUC - Hệ thống quản lý đồ án cho giảng viên và sinh viên của trường đại học FPT",
        createBy: "Vu Le",
        code: "ABC",
        status: "Assigned",
        abbreviations: "FUC",
        vietnameseTitle: "Hệ thống quản lý đồ án cho giảng viên và sinh viên của trường đại học FPT",
        profession: "Information Technology",
        specialty: "Software Engineering",
        description:
            "FUC is designed to solve the challenges that FPT students face by providing an intuitive and powerful platform specifically designed for students to learn all the information and requirements of the subject, and search for information about the instructor. Mentors can manage their groups in charge, assign tasks, exchange information and schedule meetings with groups In addition, FUC also provides students with a number of features to help students stay organized and on track, features such as task lists, calendars, and progress tracking will enable students to monitor their project's progress and identify potential roadblocks; scheduling to simplify the process of booking meetings with advisors and team members,students can easily propose meeting times and receive notifications about upcoming meetings.",
        supervisor: {
            name: "Vu Le",
            email: "vule6@fpt.edu.vn",
        },
    },
    {
        enName: "E-Learning Platform for FPT University",
        vnName: "Nền tảng học trực tuyến cho Đại học FPT",
        createBy: "Nguyen Van A",
        code: "DEF",
        status: "Unassigned",
        abbreviations: "ELP",
        vietnameseTitle: "Nền tảng học trực tuyến cho Đại học FPT",
        profession: "Information Technology",
        specialty: "E-Learning",
        description:
            "The E-Learning Platform is designed to provide a comprehensive online learning experience for FPT University students. It includes features such as video lectures, interactive quizzes, discussion forums, and assignment submissions. The platform aims to enhance the learning experience by providing a flexible and accessible way for students to engage with course materials and interact with instructors and peers.",
        supervisor: {
            name: "Nguyen Van A",
            email: "nguyenvana@fpt.edu.vn",
        },
    },
    {
        enName: "Library Management System for FPT University",
        vnName: "Hệ thống quản lý thư viện cho Đại học FPT",
        createBy: "Tran Thi B",
        code: "GHI",
        status: "Completed",
        abbreviations: "LMS",
        vietnameseTitle: "Hệ thống quản lý thư viện cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Library Management",
        description:
            "The Library Management System is designed to streamline the management of library resources at FPT University. It includes features such as book cataloging, member management, book lending and returning, and overdue notifications. The system aims to improve the efficiency of library operations and provide a better experience for library users.",
        supervisor: {
            name: "Tran Thi B",
            email: "tranthib@fpt.edu.vn",
        },
    },
    {
        enName: "Student Attendance System for FPT University",
        vnName: "Hệ thống điểm danh sinh viên cho Đại học FPT",
        createBy: "Le Van C",
        code: "JKL",
        status: "Unassigned",
        abbreviations: "SAS",
        vietnameseTitle: "Hệ thống điểm danh sinh viên cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Attendance Management",
        description:
            "The Student Attendance System is designed to automate the process of recording and managing student attendance at FPT University. It includes features such as attendance tracking, reporting, and notifications. The system aims to reduce the administrative burden on instructors and improve the accuracy of attendance records.",
        supervisor: {
            name: "Le Van C",
            email: "levanc@fpt.edu.vn",
        },
    },
    {
        enName: "Online Examination System for FPT University",
        vnName: "Hệ thống thi trực tuyến cho Đại học FPT",
        createBy: "Pham Thi D",
        code: "MNO",
        status: "Assigned",
        abbreviations: "OES",
        vietnameseTitle: "Hệ thống thi trực tuyến cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Examination Management",
        description:
            "The Online Examination System is designed to facilitate the administration of online exams at FPT University. It includes features such as exam creation, scheduling, proctoring, and result analysis. The system aims to provide a secure and efficient way for students to take exams remotely and for instructors to manage the examination process.",
        supervisor: {
            name: "Pham Thi D",
            email: "phamthid@fpt.edu.vn",
        },
    },
    {
        enName: "Course Registration System for FPT University",
        vnName: "Hệ thống đăng ký khóa học cho Đại học FPT",
        createBy: "Hoang Van E",
        code: "PQR",
        status: "Unassigned",
        abbreviations: "CRS",
        vietnameseTitle: "Hệ thống đăng ký khóa học cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Course Management",
        description:
            "The Course Registration System is designed to streamline the process of course registration for FPT University students. It includes features such as course catalog browsing, registration, waitlisting, and schedule management. The system aims to provide a user-friendly and efficient way for students to register for courses and manage their academic schedules.",
        supervisor: {
            name: "Hoang Van E",
            email: "hoangvane@fpt.edu.vn",
        },
    },
    {
        enName: "Alumni Management System for FPT University",
        vnName: "Hệ thống quản lý cựu sinh viên cho Đại học FPT",
        createBy: "Nguyen Thi F",
        code: "STU",
        status: "Completed",
        abbreviations: "AMS",
        vietnameseTitle: "Hệ thống quản lý cựu sinh viên cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Alumni Management",
        description:
            "The Alumni Management System is designed to facilitate the management of alumni relations at FPT University. It includes features such as alumni database management, event planning, and communication tools. The system aims to strengthen the connection between the university and its alumni and support alumni engagement initiatives.",
        supervisor: {
            name: "Nguyen Thi F",
            email: "nguyenthif@fpt.edu.vn",
        },
    },
    {
        enName: "Student Portal for FPT University",
        vnName: "Cổng thông tin sinh viên cho Đại học FPT",
        createBy: "Tran Van G",
        code: "VWX",
        status: "Unassigned",
        abbreviations: "SP",
        vietnameseTitle: "Cổng thông tin sinh viên cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Student Management",
        description:
            "The Student Portal is designed to provide a centralized platform for FPT University students to access academic and administrative services. It includes features such as grade viewing, course materials, announcements, and fee payment. The portal aims to enhance the student experience by providing easy access to important information and services.",
        supervisor: {
            name: "Tran Van G",
            email: "tranvang@fpt.edu.vn",
        },
    },
    {
        enName: "Research Management System for FPT University",
        vnName: "Hệ thống quản lý nghiên cứu cho Đại học FPT",
        createBy: "Le Thi H",
        code: "YZA",
        status: "Assigned",
        abbreviations: "RMS",
        vietnameseTitle: "Hệ thống quản lý nghiên cứu cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Research Management",
        description:
            "The Research Management System is designed to support the management of research projects at FPT University. It includes features such as project tracking, funding management, and collaboration tools. The system aims to streamline the research process and enhance collaboration among researchers.",
        supervisor: {
            name: "Le Thi H",
            email: "lethih@fpt.edu.vn",
        },
    },
    {
        enName: "Internship Management System for FPT University",
        vnName: "Hệ thống quản lý thực tập cho Đại học FPT",
        createBy: "Pham Van I",
        code: "BCD",
        status: "Unassigned",
        abbreviations: "IMS",
        vietnameseTitle: "Hệ thống quản lý thực tập cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Internship Management",
        description:
            "The Internship Management System is designed to facilitate the management of internship programs at FPT University. It includes features such as internship placement, progress tracking, and evaluation. The system aims to provide a structured and efficient way for students to find and complete internships, and for the university to monitor and assess their progress.",
        supervisor: {
            name: "Pham Van I",
            email: "phamvani@fpt.edu.vn",
        },
    },
    {
        enName: "Campus Management System for FPT University",
        vnName: "Hệ thống quản lý cơ sở cho Đại học FPT",
        createBy: "Nguyen Van J",
        code: "EFG",
        status: "Assigned",
        abbreviations: "CMS",
        vietnameseTitle: "Hệ thống quản lý cơ sở cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Campus Management",
        description:
            "The Campus Management System is designed to streamline the management of campus resources at FPT University. It includes features such as facility booking, maintenance tracking, and resource allocation. The system aims to improve the efficiency of campus operations and provide a better experience for students and staff.",
        supervisor: {
            name: "Nguyen Van J",
            email: "nguyenvanj@fpt.edu.vn",
        },
    },
    {
        enName: "Event Management System for FPT University",
        vnName: "Hệ thống quản lý sự kiện cho Đại học FPT",
        createBy: "Tran Thi K",
        code: "HIJ",
        status: "Unassigned",
        abbreviations: "EMS",
        vietnameseTitle: "Hệ thống quản lý sự kiện cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Event Management",
        description:
            "The Event Management System is designed to facilitate the planning and execution of events at FPT University. It includes features such as event scheduling, registration, and feedback collection. The system aims to provide a structured and efficient way for organizing events and engaging participants.",
        supervisor: {
            name: "Tran Thi K",
            email: "tranthik@fpt.edu.vn",
        },
    },
    {
        enName: "Financial Management System for FPT University",
        vnName: "Hệ thống quản lý tài chính cho Đại học FPT",
        createBy: "Le Van L",
        code: "KLM",
        status: "Assigned",
        abbreviations: "FMS",
        vietnameseTitle: "Hệ thống quản lý tài chính cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Financial Management",
        description:
            "The Financial Management System is designed to streamline the financial operations at FPT University. It includes features such as budgeting, expense tracking, and financial reporting. The system aims to improve the accuracy and efficiency of financial management and provide better financial insights.",
        supervisor: {
            name: "Le Van L",
            email: "levanl@fpt.edu.vn",
        },
    },
    {
        enName: "Human Resources Management System for FPT University",
        vnName: "Hệ thống quản lý nhân sự cho Đại học FPT",
        createBy: "Nguyen Thi M",
        code: "NOP",
        status: "Unassigned",
        abbreviations: "HRMS",
        vietnameseTitle: "Hệ thống quản lý nhân sự cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Human Resources Management",
        description:
            "The Human Resources Management System is designed to manage the HR operations at FPT University. It includes features such as employee records, payroll, performance evaluations, and recruitment. The system aims to improve the efficiency of HR processes and provide better support for employees.",
        supervisor: {
            name: "Nguyen Thi M",
            email: "nguyenthim@fpt.edu.vn",
        },
    },
    {
        enName: "Inventory Management System for FPT University",
        vnName: "Hệ thống quản lý kho cho Đại học FPT",
        createBy: "Tran Van N",
        code: "QRS",
        status: "Assigned",
        abbreviations: "IMS",
        vietnameseTitle: "Hệ thống quản lý kho cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Inventory Management",
        description:
            "The Inventory Management System is designed to manage the inventory of resources at FPT University. It includes features such as stock tracking, order management, and inventory reporting. The system aims to improve the accuracy and efficiency of inventory management and reduce the risk of stockouts.",
        supervisor: {
            name: "Tran Van N",
            email: "tranvann@fpt.edu.vn",
        },
    },
    {
        enName: "Learning Management System for FPT University",
        vnName: "Hệ thống quản lý học tập cho Đại học FPT",
        createBy: "Le Thi O",
        code: "TUV",
        status: "Unassigned",
        abbreviations: "LMS",
        vietnameseTitle: "Hệ thống quản lý học tập cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Learning Management",
        description:
            "The Learning Management System is designed to manage the learning activities at FPT University. It includes features such as course management, student tracking, and assessment. The system aims to improve the learning experience for students and provide better support for instructors.",
        supervisor: {
            name: "Le Thi O",
            email: "lethio@fpt.edu.vn",
        },
    },
    {
        enName: "Project Management System for FPT University",
        vnName: "Hệ thống quản lý dự án cho Đại học FPT",
        createBy: "Nguyen Van P",
        code: "WXY",
        status: "Assigned",
        abbreviations: "PMS",
        vietnameseTitle: "Hệ thống quản lý dự án cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Project Management",
        description:
            "The Project Management System is designed to manage the projects at FPT University. It includes features such as project planning, task management, and progress tracking. The system aims to improve the efficiency of project management and provide better visibility into project status.",
        supervisor: {
            name: "Nguyen Van P",
            email: "nguyenvanp@fpt.edu.vn",
        },
    },
    {
        enName: "Research Management System for FPT University",
        vnName: "Hệ thống quản lý nghiên cứu cho Đại học FPT",
        createBy: "Tran Thi Q",
        code: "ZAB",
        status: "Unassigned",
        abbreviations: "RMS",
        vietnameseTitle: "Hệ thống quản lý nghiên cứu cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Research Management",
        description:
            "The Research Management System is designed to manage the research activities at FPT University. It includes features such as research project tracking, funding management, and collaboration tools. The system aims to improve the efficiency of research management and enhance collaboration among researchers.",
        supervisor: {
            name: "Tran Thi Q",
            email: "tranthiq@fpt.edu.vn",
        },
    },
    {
        enName: "Student Information System for FPT University",
        vnName: "Hệ thống thông tin sinh viên cho Đại học FPT",
        createBy: "Le Van R",
        code: "CDE",
        status: "Assigned",
        abbreviations: "SIS",
        vietnameseTitle: "Hệ thống thông tin sinh viên cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Student Information Management",
        description:
            "The Student Information System is designed to manage the student information at FPT University. It includes features such as student records, enrollment, and academic performance tracking. The system aims to improve the accuracy and efficiency of student information management and provide better support for students.",
        supervisor: {
            name: "Le Van R",
            email: "levanr@fpt.edu.vn",
        },
    },
    {
        enName: "Timetable Management System for FPT University",
        vnName: "Hệ thống quản lý thời khóa biểu cho Đại học FPT",
        createBy: "Nguyen Thi S",
        code: "FGH",
        status: "Unassigned",
        abbreviations: "TMS",
        vietnameseTitle: "Hệ thống quản lý thời khóa biểu cho Đại học FPT",
        profession: "Information Technology",
        specialty: "Timetable Management",
        description:
            "The Timetable Management System is designed to manage the timetables at FPT University. It includes features such as timetable creation, scheduling, and conflict resolution. The system aims to improve the efficiency of timetable management and provide better support for students and instructors.",
        supervisor: {
            name: "Nguyen Thi S",
            email: "nguyenthis@fpt.edu.vn",
        },
    },
];