export const data = [
  {
    id: "1",
    name: "Nguyễn Văn A",
    email: "nguyenvana@gmail.com",
    campus: "Hồ Chí Minh",
    status: "Active",
  },
  {
    id: "2",
    name: "Trần Thị B",
    email: "tranthib@gmail.com",
    campus: "Hòa Lạc",
    status: "Inactive",
  },
  {
    id: "3",
    name: "Lê Văn C",
    email: "levanc@gmail.com",
    campus: "Đà Nẵng",
    status: "Active",
  },
  {
    id: "4",
    name: "Phạm Thị D",
    email: "phamthid@gmail.com",
    campus: "Quy Nhơn",
    status: "Active",
  },
  {
    id: "5",
    name: "Hoàng Văn E",
    email: "hoangvane@gmail.com",
    campus: "Cần Thơ",
    status: "Inactive",
  },
  {
    id: "6",
    name: "Đỗ Thị F",
    email: "dothif@gmail.com",
    campus: "Hồ Chí Minh",
    status: "Active",
  },
  {
    id: "7",
    name: "Võ Văn G",
    email: "vovang@gmail.com",
    campus: "Hòa Lạc",
    status: "Inactive",
  },
  {
    id: "8",
    name: "Ngô Thị H",
    email: "ngothih@gmail.com",
    campus: "Đà Nẵng",
    status: "Active",
  },
  {
    id: "9",
    name: "Bùi Văn I",
    email: "buivani@gmail.com",
    campus: "Quy Nhơn",
    status: "Active",
  },
  {
    id: "10",
    name: "Nguyễn Thị J",
    email: "nguyenthij@gmail.com",
    campus: "Cần Thơ",
    status: "Inactive",
  },
  {
    id: "11",
    name: "Phan Văn K",
    email: "phanvank@gmail.com",
    campus: "Hồ Chí Minh",
    status: "Active",
  },
  {
    id: "12",
    name: "Hồ Thị L",
    email: "hothil@gmail.com",
    campus: "Hòa Lạc",
    status: "Active",
  },
  {
    id: "13",
    name: "Trịnh Văn M",
    email: "trinhvanm@gmail.com",
    campus: "Đà Nẵng",
    status: "Inactive",
  },
  {
    id: "14",
    name: "Đặng Thị N",
    email: "dangthin@gmail.com",
    campus: "Quy Nhơn",
    status: "Active",
  },
  {
    id: "15",
    name: "Lý Văn O",
    email: "lyvano@gmail.com",
    campus: "Cần Thơ",
    status: "Active",
  },
  {
    id: "16",
    name: "Nguyễn Văn P",
    email: "nguyenvanp@gmail.com",
    campus: "Hồ Chí Minh",
    status: "Inactive",
  },
  {
    id: "17",
    name: "Lê Thị Q",
    email: "lethiq@gmail.com",
    campus: "Hòa Lạc",
    status: "Active",
  },
  {
    id: "18",
    name: "Phạm Văn R",
    email: "phamvanr@gmail.com",
    campus: "Đà Nẵng",
    status: "Active",
  },
  {
    id: "19",
    name: "Vũ Thị S",
    email: "vuthis@gmail.com",
    campus: "Quy Nhơn",
    status: "Inactive",
  },
  {
    id: "20",
    name: "Trần Văn T",
    email: "tranvant@gmail.com",
    campus: "Cần Thơ",
    status: "Active",
  },
];
